### ISSUE TITLE
Add method for ConTeXt

### ISSUE THREAD

**Issue by pablgonz** [PHPirates/travis-ci-latex-pdf#27]
Hi, just as an idea, I think this is interesting: 
https://tex.stackexchange.com/a/459487/7832
Saludos

**Comment by PHPirates** [comment]
Hi again, true I should really look into ConTeXt, thanks for reminding me! Maybe at some point we will have a 'travis-ci-context-pdf' repo :) but will include it here for now.

**Comment by pablgonz** [comment]
@PHPirates It will be great, by adding ConTeXt I think the TeX family will be complete :)

**Comment by PHPirates** [comment]
Nono stupid bot I'm going to do this within a few weeks...

**Comment by pablgonz** [comment]
@PHPirates See https://gitlab.com/islandoftex/images (interesting and related)
