### ISSUE TITLE
tectonic --keep-intermediates --reruns 0 ./xxxx.tex Error

### ISSUE THREAD

**Issue by cschaf** [PHPirates/travis-ci-latex-pdf#28]
Hello guys,
I followed the instructions for building with Miniconda and Tectonic. I fixed the problem with the biber version and now I get an error at the command "tectonic --keep-intermediates --reruns 0 ./MAIN_Masterthesis.tex" (see [Log](https://api.travis-ci.com/v3/job/277821898/log.txt)). I cant figure out what the problem is. Could you please help me to find and solve my issue?

Greetings
Christian

**Comment by PHPirates** [comment]
Did you actually find the error in the log? It's this one:

```
! Undefined control sequence.
l.18 \pdfminorversion
```

Is that a command that is present in your document?
If so, why is it there? I don't really know why it fails on the command though.

Can you compile your document locally with Tectonic? (Or anything else)

**Comment by PHPirates** [comment]
I searched for \pdfminorversion online and it appears to be a pdftex command. So it would make sense if you cannot use it with Tectonic (which is a xetex fork). I'd suggest removing it, as I see you use it here: https://github.com/cschaf/masterthesis/blob/664ba26a4a154cf07c16dc1c4b4d30a4176e99a8/thesis/settings/settings.tex#L18

When I try to run your file I get a `! LaTeX Error: Cannot determine size of graphic in ../images/hsb_logo.png (no B
oundingBox).` but not sure what is happening there.

**Comment by cschaf** [comment]
I used this commands. After I commended \pdfminorversion=6 out, the build process has finished succesfully.
% PDF-Kompression
\pdfminorversion=6
%\pdfobjcompresslevel=1

**Comment by PHPirates** [comment]
That's good to hear, thanks for reporting back! I'll close this, unless you have further questions.
